name: onfido_sdk
description: This library aims to help flutter developers integrating with the Onfido SDK.
version: 4.2.0
homepage: https://onfido.com/
repository: https://github.com/onfido/flutter-sdk/

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.onfido.sdk.flutter
        pluginClass: OnfidoPlugin
      ios:
        pluginClass: OnfidoSdkPlugin